const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    animationDistanceThreshold: 5,
    arch: 'x64',
    baseUrl: null,
    blockHosts: null,
    browsers: [
      {
        name: 'chrome',
        family: 'chromium',
        channel: 'stable',
        displayName: 'Chrome',
        version: '117.0.5938.149',
        path: 'C:\Program Files\Google\Chrome\Application\chrome.exe',
        minSupportedVersion: 64,
        majorVersion: '117',
      },
      {
        name: 'chrome',
        family: 'chromium',
        channel: 'beta',
        displayName: 'Chrome Beta',
        version: '118.0.5993.54',
        path: 'C:\Program Files\Google\Chrome Beta\Application\chrome.exe',
        minSupportedVersion: 64,
        majorVersion: '118',
      },
      {
        name: 'edge',
        family: 'chromium',
        channel: 'stable',
        displayName: 'Edge',
        version: '117.0.2045.55',
        path: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe',
        minSupportedVersion: 79,
        majorVersion: '117',
      },
      {
        name: 'edge',
        family: 'chromium',
        channel: 'beta',
        displayName: 'Edge Beta',
        version: '118.0.2088.27',
        path: 'C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe',
        minSupportedVersion: 79,
        majorVersion: '118',
      },
      {
        name: 'electron',
        channel: 'stable',
        family: 'chromium',
        displayName: 'Electron',
        version: '114.0.5735.289',
        path: '',
        majorVersion: 114,
      },
    ],
    chromeWebSecurity: true,
    clientCertificates: [],
    defaultCommandTimeout: 4000,
    downloadsFolder: 'cypress/downloads',
    env: {},
    excludeSpecPattern: '*.hot-update.js',
    execTimeout: 60000,
    experimentalCspAllowList: false,
    experimentalFetchPolyfill: false,
    experimentalInteractiveRunEvents: false,
    experimentalMemoryManagement: false,
    experimentalModifyObstructiveThirdPartyCode: false,
    experimentalOriginDependencies: false,
    experimentalRunAllSpecs: false,
    experimentalSkipDomainInjection: null,
    experimentalSourceRewriting: false,
    experimentalStudio: false,
    experimentalWebKitSupport: false,
    fileServerFolder: '',
    fixturesFolder: 'cypress/fixtures',
    hosts: null,
    includeShadowDom: false,
    isInteractive: true,
    keystrokeDelay: 0,
    modifyObstructiveCode: true,
    numTestsKeptInMemory: 50,
    pageLoadTimeout: 60000,
    platform: 'win32',
    port: null,
    projectId: null,
    redirectionLimit: 20,
    reporter: 'spec',
    reporterOptions: null,
    requestTimeout: 5000,
    resolvedNodePath: null,
    resolvedNodeVersion: null,
    responseTimeout: 30000,
    retries: {
      runMode: 0,
      openMode: 0,
    },
    screenshotOnRunFailure: true,
    screenshotsFolder: 'cypress/screenshots',
    scrollBehavior: 'top',
    slowTestThreshold: 10000,
    specPattern: '**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'cypress/support/e2e.{js,jsx,ts,tsx}',
    supportFolder: false,
    taskTimeout: 60000,
    testIsolation: true,
    trashAssetsBeforeRuns: true,
    userAgent: null,
    video: false,
    videoCompression: false,
    videosFolder: 'cypress/videos',
    viewportHeight: 660,
    viewportWidth: 1000,
    waitForAnimations: true,
    watchForFileChanges: true,
  },

  component: {
    devServer: {
      framework: "angular",
      bundler: "webpack",
    },
    specPattern: "**/*.cy.ts",
  },
});
